-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.1
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity p_hls_fptosi_double_s is
port (
    x : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of p_hls_fptosi_double_s is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_C01 : STD_LOGIC_VECTOR (11 downto 0) := "110000000001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_73 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110011";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal p_Val2_s_fu_44_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal loc_V_1_fu_66_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_i_i_fu_70_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal loc_V_fu_56_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_i_i_i_cast1_fu_84_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_assign_fu_88_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_1_i_i_fu_102_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal isNeg_fu_94_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_i_i_cast_fu_108_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_assign_1_fu_112_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_assign_1_cast_fu_120_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_i_i_cast_fu_128_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_i_i_cast_fu_80_p1 : STD_LOGIC_VECTOR (168 downto 0);
    signal tmp_2_i_i_fu_124_p1 : STD_LOGIC_VECTOR (168 downto 0);
    signal tmp_3_i_i_fu_132_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_fu_144_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_i_i_fu_138_p2 : STD_LOGIC_VECTOR (168 downto 0);
    signal tmp_1_fu_152_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_2_fu_156_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal p_Val2_2_fu_166_p3 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_6_i_i_fu_174_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_s_fu_48_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_i_i_fu_178_p2 : STD_LOGIC_VECTOR (63 downto 0);


begin



    ap_return <= 
        tmp_9_i_i_fu_178_p2 when (p_Result_s_fu_48_p3(0) = '1') else 
        tmp_6_i_i_fu_174_p1;
    isNeg_fu_94_p3 <= sh_assign_fu_88_p2(11 downto 11);
    loc_V_1_fu_66_p1 <= p_Val2_s_fu_44_p1(52 - 1 downto 0);
    loc_V_fu_56_p4 <= p_Val2_s_fu_44_p1(62 downto 52);
    p_Result_s_fu_48_p3 <= p_Val2_s_fu_44_p1(63 downto 63);
    p_Val2_2_fu_166_p3 <= 
        tmp_1_fu_152_p1 when (isNeg_fu_94_p3(0) = '1') else 
        tmp_2_fu_156_p4;
    p_Val2_s_fu_44_p1 <= x;
        sh_assign_1_cast_fu_120_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sh_assign_1_fu_112_p3),32));

    sh_assign_1_fu_112_p3 <= 
        tmp_1_i_i_cast_fu_108_p1 when (isNeg_fu_94_p3(0) = '1') else 
        sh_assign_fu_88_p2;
    sh_assign_fu_88_p2 <= std_logic_vector(signed(ap_const_lv12_C01) + signed(tmp_i_i_i_cast1_fu_84_p1));
    tmp_1_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_144_p3),63));
        tmp_1_i_i_cast_fu_108_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_i_i_fu_102_p2),12));

    tmp_1_i_i_fu_102_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(loc_V_fu_56_p4));
    tmp_2_fu_156_p4 <= tmp_4_i_i_fu_138_p2(115 downto 53);
    tmp_2_i_i_cast_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sh_assign_1_cast_fu_120_p1),54));
    tmp_2_i_i_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sh_assign_1_cast_fu_120_p1),169));
    tmp_3_i_i_fu_132_p2 <= std_logic_vector(shift_right(unsigned(tmp_i_i_fu_70_p4),to_integer(unsigned('0' & tmp_2_i_i_cast_fu_128_p1(31-1 downto 0)))));
    tmp_4_i_i_fu_138_p2 <= std_logic_vector(shift_left(unsigned(tmp_i_i_cast_fu_80_p1),to_integer(unsigned('0' & tmp_2_i_i_fu_124_p1(31-1 downto 0)))));
    tmp_6_i_i_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_2_fu_166_p3),64));
    tmp_9_i_i_fu_178_p2 <= std_logic_vector(unsigned(ap_const_lv64_0) - unsigned(tmp_6_i_i_fu_174_p1));
    tmp_fu_144_p3 <= tmp_3_i_i_fu_132_p2(53 downto 53);
    tmp_i_i_cast_fu_80_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_i_i_fu_70_p4),169));
    tmp_i_i_fu_70_p4 <= ((ap_const_lv1_1 & loc_V_1_fu_66_p1) & ap_const_lv1_0);
    tmp_i_i_i_cast1_fu_84_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loc_V_fu_56_p4),12));
end behav;
