#pragma line 1 "astro.c" ::: -10
#pragma line 1 "astro.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/home/linsun/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/home/linsun/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "astro.c" 2 ::: 184
#pragma line 1 "./astro.h" 1 ::: 185
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 189
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 217
#pragma line 122 "/usr/include/features.h" 3 4 ::: 314
#pragma line 156 "/usr/include/features.h" 3 4 ::: 339
#pragma line 180 "/usr/include/features.h" 3 4 ::: 341
#pragma line 191 "/usr/include/features.h" 3 4 ::: 344
#pragma line 343 "/usr/include/features.h" 3 4 ::: 375
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 379
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 414
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 421
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 444
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 485
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 491
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 509
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 515
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 519
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 521
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 525
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 535
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 588
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 629
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 654
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 678
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 679
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 681
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 683
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 684
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 709
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 720
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 725
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 726
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 727
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 733
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 774
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 777
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 779
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 807
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 809
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 811
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 872
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 879
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 897
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 902
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 913
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 982
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 996
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 999
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1000
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1032
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1048
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1073
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1076
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1081
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1103
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1124
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1127
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1138
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1148
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1150
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1154
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1203
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1204
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1210
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1212
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1232
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1243
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1284
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1314
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1340
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1344
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1359
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1371
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1377
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1379
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1389
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1411
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1427
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1444
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1476
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1522
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1536
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1539
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1615
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1654
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1695
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1808
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1871
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1920
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1931
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1961
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1989
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2021
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2033
#pragma line 5 "./astro.h" 2 ::: 2036
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2037
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2070
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2095
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2098
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2108
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2137
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2155
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2156
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2212
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2213
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2250
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2252
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2256
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2259
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2277
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2278
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2280
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2282
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2290
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2308
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2311
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2314
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2316
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2317
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2351
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2357
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2373
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2375
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2497
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2511
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2532
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2549
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2571
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2579
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2588
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2589
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2610
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2613
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2616
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2619
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2622
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2623
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2624
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2649
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2652
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2662
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2697
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2728
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2751
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2753
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 2755
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2756
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 2760
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2800
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2811
#pragma line 118 "/usr/include/time.h" 3 4 ::: 2832
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2840
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 2842
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2877
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2922
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2952
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 2956
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2974
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2985
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2987
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3009
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3013
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3035
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3037
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3039
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3040
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3063
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3085
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3162
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3193
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3194
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3337
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3366
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3391
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3416
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3419
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3428
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3441
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3448
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3460
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3471
#pragma line 634 "/usr/include/stdlib.h" 3 4 ::: 3517
#pragma line 657 "/usr/include/stdlib.h" 3 4 ::: 3526
#pragma line 712 "/usr/include/stdlib.h" 3 4 ::: 3533
#pragma line 728 "/usr/include/stdlib.h" 3 4 ::: 3539
#pragma line 752 "/usr/include/stdlib.h" 3 4 ::: 3554
#pragma line 911 "/usr/include/stdlib.h" 3 4 ::: 3705
#pragma line 947 "/usr/include/stdlib.h" 3 4 ::: 3707
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 3716
#pragma line 955 "/usr/include/stdlib.h" 2 3 4 ::: 3734
#pragma line 6 "./astro.h" 2 ::: 3737
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 3738
#pragma line 30 "/usr/include/math.h" 3 4 ::: 3760
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 3763
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 3789
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 3821
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 3822
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 3827
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 3852
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 3854
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 3879
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 3880
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 3899
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 3903
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 3927
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 3931
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 3956
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 3961
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 3978
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 3984
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 3991
#pragma line 83 "/usr/include/math.h" 3 4 ::: 3997
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 3998
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4075
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4105
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4346
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 4349
#pragma line 93 "/usr/include/math.h" 3 4 ::: 4350
#pragma line 104 "/usr/include/math.h" 3 4 ::: 4353
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4354
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4431
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4461
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4702
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 4705
#pragma line 139 "/usr/include/math.h" 3 4 ::: 4706
#pragma line 151 "/usr/include/math.h" 3 4 ::: 4709
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4710
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4787
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4817
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5058
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 5061
#pragma line 167 "/usr/include/math.h" 3 4 ::: 5062
#pragma line 248 "/usr/include/math.h" 3 4 ::: 5129
#pragma line 268 "/usr/include/math.h" 3 4 ::: 5131
#pragma line 282 "/usr/include/math.h" 3 4 ::: 5133
#pragma line 304 "/usr/include/math.h" 3 4 ::: 5143
#pragma line 318 "/usr/include/math.h" 3 4 ::: 5145
#pragma line 346 "/usr/include/math.h" 3 4 ::: 5153
#pragma line 411 "/usr/include/math.h" 3 4 ::: 5207
#pragma line 428 "/usr/include/math.h" 3 4 ::: 5209
#pragma line 448 "/usr/include/math.h" 3 4 ::: 5213
#pragma line 470 "/usr/include/math.h" 3 4 ::: 5228
#pragma line 7 "./astro.h" 2 ::: 5284
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 5285
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 5319
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 5346
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 5378
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 5379
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 5381
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 5383
#pragma line 47 "/usr/include/stdint.h" 3 4 ::: 5390
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 5452
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 5460
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 5465
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 5505
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 5507
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 5509
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 5511
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 5524
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 5530
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 5543
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 5545
#pragma line 34 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 5547
#pragma line 8 "./astro.h" 2 ::: 5548
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 5549
#pragma line 29 "/usr/include/string.h" 3 4 ::: 5570
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5575
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5600
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 5603
#pragma line 92 "/usr/include/string.h" 3 4 ::: 5640
#pragma line 124 "/usr/include/string.h" 3 4 ::: 5643
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 5680
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 5723
#pragma line 207 "/usr/include/string.h" 3 4 ::: 5745
#pragma line 231 "/usr/include/string.h" 3 4 ::: 5747
#pragma line 258 "/usr/include/string.h" 3 4 ::: 5752
#pragma line 278 "/usr/include/string.h" 3 4 ::: 5755
#pragma line 310 "/usr/include/string.h" 3 4 ::: 5765
#pragma line 337 "/usr/include/string.h" 3 4 ::: 5770
#pragma line 393 "/usr/include/string.h" 3 4 ::: 5791
#pragma line 439 "/usr/include/string.h" 3 4 ::: 5822
#pragma line 484 "/usr/include/string.h" 3 4 ::: 5845
#pragma line 512 "/usr/include/string.h" 3 4 ::: 5851
#pragma line 550 "/usr/include/string.h" 3 4 ::: 5875
#pragma line 9 "./astro.h" 2 ::: 5901
#pragma line 2 "astro.c" 2 ::: 5944
