#pragma line 1 "astro.c" ::: 0
#pragma line 1 "astro.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/home/linsun/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/home/linsun/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "astro.c" 2 ::: 194
#pragma line 1 "./astro.h" 1 ::: 195
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 199
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 227
#pragma line 122 "/usr/include/features.h" 3 4 ::: 324
#pragma line 156 "/usr/include/features.h" 3 4 ::: 349
#pragma line 180 "/usr/include/features.h" 3 4 ::: 351
#pragma line 191 "/usr/include/features.h" 3 4 ::: 354
#pragma line 343 "/usr/include/features.h" 3 4 ::: 385
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 389
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 424
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 431
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 454
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 495
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 501
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 519
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 525
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 529
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 531
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 535
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 545
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 598
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 639
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 664
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 688
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 689
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 691
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 693
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 694
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 719
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 730
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 735
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 736
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 737
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 743
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 784
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 787
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 789
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 817
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 819
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 821
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 882
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 889
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 907
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 912
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 923
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 992
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1006
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1009
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1010
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1042
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1058
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1083
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1086
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1091
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1113
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1134
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1137
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1148
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1158
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1160
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1164
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1213
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1214
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1220
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1222
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1242
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1253
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1294
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1324
#pragma line 385 "/usr/include/libio.h" 3 4 ::: 1350
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1354
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1369
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1381
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1387
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1389
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1399
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1421
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1437
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1454
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1486
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1532
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1546
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1549
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1625
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1664
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1705
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1818
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1881
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1930
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1941
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1971
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1999
#pragma line 909 "/usr/include/stdio.h" 3 4 ::: 2031
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2043
#pragma line 5 "./astro.h" 2 ::: 2046
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2047
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2080
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2105
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2108
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2118
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2147
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2165
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2166
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2222
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2223
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2260
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2262
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2266
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2269
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2287
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2288
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2290
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2292
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2300
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2318
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2321
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2324
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2326
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2327
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2361
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2367
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2383
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2385
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2507
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2521
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2542
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2559
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2581
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2589
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2598
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2599
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2620
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2623
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2626
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2629
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2632
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2633
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2634
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2659
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2662
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2672
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2707
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2738
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2761
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2763
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 2765
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2766
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 2770
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2810
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2821
#pragma line 118 "/usr/include/time.h" 3 4 ::: 2842
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2850
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 2852
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2887
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2932
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2962
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 2966
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2984
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2995
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2997
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3019
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3023
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3045
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3047
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3049
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3050
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3073
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3095
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3172
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3203
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3204
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3347
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3376
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3401
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3426
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3429
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3438
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3451
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3458
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3470
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3481
#pragma line 634 "/usr/include/stdlib.h" 3 4 ::: 3527
#pragma line 657 "/usr/include/stdlib.h" 3 4 ::: 3536
#pragma line 712 "/usr/include/stdlib.h" 3 4 ::: 3543
#pragma line 728 "/usr/include/stdlib.h" 3 4 ::: 3549
#pragma line 752 "/usr/include/stdlib.h" 3 4 ::: 3564
#pragma line 911 "/usr/include/stdlib.h" 3 4 ::: 3715
#pragma line 947 "/usr/include/stdlib.h" 3 4 ::: 3717
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 3726
#pragma line 955 "/usr/include/stdlib.h" 2 3 4 ::: 3744
#pragma line 6 "./astro.h" 2 ::: 3747
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 3748
#pragma line 30 "/usr/include/math.h" 3 4 ::: 3770
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 3773
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 3799
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 3831
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 3832
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 3837
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 3862
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 3864
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 3889
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 3890
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 3909
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 3913
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 3937
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 3941
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 3966
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 3971
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 3988
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 3994
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 4001
#pragma line 83 "/usr/include/math.h" 3 4 ::: 4007
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4008
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4085
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4115
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4356
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 4359
#pragma line 93 "/usr/include/math.h" 3 4 ::: 4360
#pragma line 104 "/usr/include/math.h" 3 4 ::: 4363
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4364
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4441
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4471
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4712
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 4715
#pragma line 139 "/usr/include/math.h" 3 4 ::: 4716
#pragma line 151 "/usr/include/math.h" 3 4 ::: 4719
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4720
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4797
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 4827
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 5068
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 5071
#pragma line 167 "/usr/include/math.h" 3 4 ::: 5072
#pragma line 248 "/usr/include/math.h" 3 4 ::: 5139
#pragma line 268 "/usr/include/math.h" 3 4 ::: 5141
#pragma line 282 "/usr/include/math.h" 3 4 ::: 5143
#pragma line 304 "/usr/include/math.h" 3 4 ::: 5153
#pragma line 318 "/usr/include/math.h" 3 4 ::: 5155
#pragma line 346 "/usr/include/math.h" 3 4 ::: 5163
#pragma line 411 "/usr/include/math.h" 3 4 ::: 5217
#pragma line 428 "/usr/include/math.h" 3 4 ::: 5219
#pragma line 448 "/usr/include/math.h" 3 4 ::: 5223
#pragma line 470 "/usr/include/math.h" 3 4 ::: 5238
#pragma line 7 "./astro.h" 2 ::: 5294
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 5295
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 5329
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 5356
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 5388
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 5389
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 5391
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 5393
#pragma line 47 "/usr/include/stdint.h" 3 4 ::: 5400
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 5462
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 5470
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 5475
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 5515
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 5517
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 5519
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 5521
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 5534
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 5540
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 5553
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 5555
#pragma line 34 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 5557
#pragma line 8 "./astro.h" 2 ::: 5558
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 5559
#pragma line 29 "/usr/include/string.h" 3 4 ::: 5580
#pragma line 1 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5585
#pragma line 56 "/home/linsun/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5610
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 5613
#pragma line 92 "/usr/include/string.h" 3 4 ::: 5650
#pragma line 124 "/usr/include/string.h" 3 4 ::: 5653
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 5690
#pragma line 160 "/usr/include/string.h" 2 3 4 ::: 5733
#pragma line 207 "/usr/include/string.h" 3 4 ::: 5755
#pragma line 231 "/usr/include/string.h" 3 4 ::: 5757
#pragma line 258 "/usr/include/string.h" 3 4 ::: 5762
#pragma line 278 "/usr/include/string.h" 3 4 ::: 5765
#pragma line 310 "/usr/include/string.h" 3 4 ::: 5775
#pragma line 337 "/usr/include/string.h" 3 4 ::: 5780
#pragma line 393 "/usr/include/string.h" 3 4 ::: 5801
#pragma line 439 "/usr/include/string.h" 3 4 ::: 5832
#pragma line 484 "/usr/include/string.h" 3 4 ::: 5855
#pragma line 512 "/usr/include/string.h" 3 4 ::: 5861
#pragma line 550 "/usr/include/string.h" 3 4 ::: 5885
#pragma line 9 "./astro.h" 2 ::: 5911
#pragma line 2 "astro.c" 2 ::: 5954
