// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XASTROSIM_H
#define XASTROSIM_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xastrosim_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XAstrosim_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XAstrosim;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XAstrosim_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XAstrosim_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XAstrosim_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XAstrosim_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XAstrosim_Initialize(XAstrosim *InstancePtr, u16 DeviceId);
XAstrosim_Config* XAstrosim_LookupConfig(u16 DeviceId);
int XAstrosim_CfgInitialize(XAstrosim *InstancePtr, XAstrosim_Config *ConfigPtr);
#else
int XAstrosim_Initialize(XAstrosim *InstancePtr, const char* InstanceName);
int XAstrosim_Release(XAstrosim *InstancePtr);
#endif

void XAstrosim_Start(XAstrosim *InstancePtr);
u32 XAstrosim_IsDone(XAstrosim *InstancePtr);
u32 XAstrosim_IsIdle(XAstrosim *InstancePtr);
u32 XAstrosim_IsReady(XAstrosim *InstancePtr);
void XAstrosim_EnableAutoRestart(XAstrosim *InstancePtr);
void XAstrosim_DisableAutoRestart(XAstrosim *InstancePtr);


void XAstrosim_InterruptGlobalEnable(XAstrosim *InstancePtr);
void XAstrosim_InterruptGlobalDisable(XAstrosim *InstancePtr);
void XAstrosim_InterruptEnable(XAstrosim *InstancePtr, u32 Mask);
void XAstrosim_InterruptDisable(XAstrosim *InstancePtr, u32 Mask);
void XAstrosim_InterruptClear(XAstrosim *InstancePtr, u32 Mask);
u32 XAstrosim_InterruptGetEnabled(XAstrosim *InstancePtr);
u32 XAstrosim_InterruptGetStatus(XAstrosim *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
