// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xastrosim.h"

extern XAstrosim_Config XAstrosim_ConfigTable[];

XAstrosim_Config *XAstrosim_LookupConfig(u16 DeviceId) {
	XAstrosim_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XASTROSIM_NUM_INSTANCES; Index++) {
		if (XAstrosim_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XAstrosim_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XAstrosim_Initialize(XAstrosim *InstancePtr, u16 DeviceId) {
	XAstrosim_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XAstrosim_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XAstrosim_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

