// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xastrosim.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAstrosim_CfgInitialize(XAstrosim *InstancePtr, XAstrosim_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAstrosim_Start(XAstrosim *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAstrosim_ReadReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_AP_CTRL) & 0x80;
    XAstrosim_WriteReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XAstrosim_IsDone(XAstrosim *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAstrosim_ReadReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XAstrosim_IsIdle(XAstrosim *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAstrosim_ReadReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XAstrosim_IsReady(XAstrosim *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAstrosim_ReadReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XAstrosim_EnableAutoRestart(XAstrosim *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAstrosim_WriteReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XAstrosim_DisableAutoRestart(XAstrosim *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAstrosim_WriteReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_AP_CTRL, 0);
}

void XAstrosim_InterruptGlobalEnable(XAstrosim *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAstrosim_WriteReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_GIE, 1);
}

void XAstrosim_InterruptGlobalDisable(XAstrosim *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAstrosim_WriteReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_GIE, 0);
}

void XAstrosim_InterruptEnable(XAstrosim *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAstrosim_ReadReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_IER);
    XAstrosim_WriteReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_IER, Register | Mask);
}

void XAstrosim_InterruptDisable(XAstrosim *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAstrosim_ReadReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_IER);
    XAstrosim_WriteReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_IER, Register & (~Mask));
}

void XAstrosim_InterruptClear(XAstrosim *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAstrosim_WriteReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_ISR, Mask);
}

u32 XAstrosim_InterruptGetEnabled(XAstrosim *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAstrosim_ReadReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_IER);
}

u32 XAstrosim_InterruptGetStatus(XAstrosim *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAstrosim_ReadReg(InstancePtr->Axilites_BaseAddress, XASTROSIM_AXILITES_ADDR_ISR);
}

