// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module p_hls_fptosi_double_s (
        x,
        ap_return
);


input  [63:0] x;
output  [63:0] ap_return;

wire   [63:0] p_Val2_s_fu_44_p1;
wire   [51:0] loc_V_1_fu_66_p1;
wire   [53:0] tmp_i_i_fu_70_p4;
wire   [10:0] loc_V_fu_56_p4;
wire   [11:0] tmp_i_i_i_cast1_fu_84_p1;
wire   [11:0] sh_assign_fu_88_p2;
wire   [10:0] tmp_1_i_i_fu_102_p2;
wire   [0:0] isNeg_fu_94_p3;
wire  signed [11:0] tmp_1_i_i_cast_fu_108_p1;
wire   [11:0] sh_assign_1_fu_112_p3;
wire  signed [31:0] sh_assign_1_cast_fu_120_p1;
wire   [53:0] tmp_2_i_i_cast_fu_128_p1;
wire   [168:0] tmp_i_i_cast_fu_80_p1;
wire   [168:0] tmp_2_i_i_fu_124_p1;
wire   [53:0] tmp_3_i_i_fu_132_p2;
wire   [0:0] tmp_fu_144_p3;
wire   [168:0] tmp_4_i_i_fu_138_p2;
wire   [62:0] tmp_1_fu_152_p1;
wire   [62:0] tmp_2_fu_156_p4;
wire   [62:0] p_Val2_2_fu_166_p3;
wire   [63:0] tmp_6_i_i_fu_174_p1;
wire   [0:0] p_Result_s_fu_48_p3;
wire   [63:0] tmp_9_i_i_fu_178_p2;

assign ap_return = ((p_Result_s_fu_48_p3[0:0] === 1'b1) ? tmp_9_i_i_fu_178_p2 : tmp_6_i_i_fu_174_p1);

assign isNeg_fu_94_p3 = sh_assign_fu_88_p2[32'd11];

assign loc_V_1_fu_66_p1 = p_Val2_s_fu_44_p1[51:0];

assign loc_V_fu_56_p4 = {{p_Val2_s_fu_44_p1[62:52]}};

assign p_Result_s_fu_48_p3 = p_Val2_s_fu_44_p1[32'd63];

assign p_Val2_2_fu_166_p3 = ((isNeg_fu_94_p3[0:0] === 1'b1) ? tmp_1_fu_152_p1 : tmp_2_fu_156_p4);

assign p_Val2_s_fu_44_p1 = x;

assign sh_assign_1_cast_fu_120_p1 = $signed(sh_assign_1_fu_112_p3);

assign sh_assign_1_fu_112_p3 = ((isNeg_fu_94_p3[0:0] === 1'b1) ? tmp_1_i_i_cast_fu_108_p1 : sh_assign_fu_88_p2);

assign sh_assign_fu_88_p2 = ($signed(12'd3073) + $signed(tmp_i_i_i_cast1_fu_84_p1));

assign tmp_1_fu_152_p1 = tmp_fu_144_p3;

assign tmp_1_i_i_cast_fu_108_p1 = $signed(tmp_1_i_i_fu_102_p2);

assign tmp_1_i_i_fu_102_p2 = (11'd1023 - loc_V_fu_56_p4);

assign tmp_2_fu_156_p4 = {{tmp_4_i_i_fu_138_p2[115:53]}};

assign tmp_2_i_i_cast_fu_128_p1 = $unsigned(sh_assign_1_cast_fu_120_p1);

assign tmp_2_i_i_fu_124_p1 = $unsigned(sh_assign_1_cast_fu_120_p1);

assign tmp_3_i_i_fu_132_p2 = tmp_i_i_fu_70_p4 >> tmp_2_i_i_cast_fu_128_p1;

assign tmp_4_i_i_fu_138_p2 = tmp_i_i_cast_fu_80_p1 << tmp_2_i_i_fu_124_p1;

assign tmp_6_i_i_fu_174_p1 = p_Val2_2_fu_166_p3;

assign tmp_9_i_i_fu_178_p2 = (64'd0 - tmp_6_i_i_fu_174_p1);

assign tmp_fu_144_p3 = tmp_3_i_i_fu_132_p2[32'd53];

assign tmp_i_i_cast_fu_80_p1 = tmp_i_i_fu_70_p4;

assign tmp_i_i_fu_70_p4 = {{{{1'd1}, {loc_V_1_fu_66_p1}}}, {1'd0}};

assign tmp_i_i_i_cast1_fu_84_p1 = loc_V_fu_56_p4;

endmodule //p_hls_fptosi_double_s
